
(()=>{
'use strict';
const ROUTES=['Початок','GIS і розумне картографування','Від рішення до просторової потреби','Комунальна будівля: що перевірити','Джерела й орієнтири','Спробуйте застосувати логіку','Завершений приклад','Ваша управлінська карта','Фінальна перевірка','Завершення'];
const PREVIOUS_LESSON_URL='https://clusterceu-crypto.github.io/UCAN-Lesson12/';
const NEXT_LESSON_URL='https://clusterceu-crypto.github.io/UCAN-Lesson14/';
const NS='ucan.l13.v1'; const qa=new URLSearchParams(location.search).get('qa')==='1';
const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const state={route:0,formative:{},portfolio:['','','','','','',''].slice(0,6),assessment:{answers:{},passed:false,dirty:false,checked:false,score:null}};
function load(){if(qa)return;try{const raw=localStorage.getItem(NS);if(raw){const v=JSON.parse(raw);if(Number.isInteger(v.route))state.route=Math.max(0,Math.min(9,v.route));if(v.formative)state.formative=v.formative;if(Array.isArray(v.portfolio)&&v.portfolio.length===6)state.portfolio=v.portfolio;if(v.assessment)state.assessment={...state.assessment,...v.assessment,answers:v.assessment.answers||{}}}}catch(e){notify('Локальне відновлення стану недоступне. Дані цієї сесії залишаються в браузері.')}}
function save(){if(qa)return false;try{localStorage.setItem(NS,JSON.stringify(state));return true}catch(e){notify('Не вдалося зберегти локальний стан. Спробуйте ще раз.');return false}}
function notify(t){const el=$('#globalStatus');el.textContent=t;el.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>el.classList.remove('show'),4200)}
function renderRoute(){ $$('.route').forEach((el,i)=>el.hidden=i!==state.route); $('#pageCount').textContent=`Сторінка ${state.route+1} із 10`; const pct=(state.route+1)*10; $('#percent').textContent=`${pct}%`; $('.progress-track').setAttribute('aria-valuenow',pct); $('#progressBar').style.width=pct+'%'; $$('.route-tab').forEach((b,i)=>{b.setAttribute('aria-current',i===state.route?'page':'false')}); $('#prevBtn').disabled=state.route===0; const assessmentOk=state.assessment.passed&&!state.assessment.dirty&&state.assessment.checked&&state.assessment.score===5; $('#nextBtn').hidden=state.route===9; $('#nextBtn').textContent=state.route===8&&assessmentOk?'До завершення →':'Далі →'; $('#nextLessonBtn').hidden=state.route!==9; if(state.route===9)renderCompletion(); if(!qa)save(); window.scrollTo({top:0,behavior:'instant'}); setTimeout(()=>$('#main').focus({preventScroll:true}),0); }
function gotoRoute(i){i=Math.max(0,Math.min(9,i)); if(!qa && i===9 && !(state.assessment.passed&&!state.assessment.dirty&&state.assessment.checked)){notify('Спочатку отримайте поточний перевірений результат 5/5 у фінальній перевірці.');state.route=8}else state.route=i;renderRoute()}
function initStrip(){const strip=$('#routeStrip');ROUTES.forEach((r,i)=>{const b=document.createElement('button');b.type='button';b.className='route-tab';b.textContent=`${i+1}. ${r}`;b.addEventListener('click',()=>qa?gotoRoute(i):gotoRoute(i));strip.appendChild(b)})}
function portfolioValues(){return [1,2,3,4,5,6].map(i=>$(`#pf${i}`).value.trim())}
function renderPortfolio(){[1,2,3,4,5,6].forEach((i)=>{$(`#pf${i}`).value=state.portfolio[i-1]||''});updateSynthesis()}
function updateSynthesis(){const vals=portfolioValues();const labels=['Управлінське рішення / питання','Просторова інформація, якої потребує рішення','Релевантні геодані / GIS-шари','Джерело / відповідальний за дані','Доступність / придатність','Використання в рішенні'];const list=$('#synthesisList');list.innerHTML='';vals.forEach((v,i)=>{const li=document.createElement('li');const s=document.createElement('strong');s.textContent=`${i+1}. ${labels[i]}: `;li.appendChild(s);li.append(document.createTextNode(v||'—'));list.appendChild(li)})}
function savePortfolio(){if(qa){$('#portfolioStatus').textContent='QA MODE: збереження вимкнено; learner-state не змінюється.';return}state.portfolio=portfolioValues();const ok=save();$('#portfolioStatus').textContent=ok?'Карту збережено локально у Вашому браузері.':'Не вдалося зберегти карту локально. Ваші поточні значення залишаються у формі цього браузера.';updateSynthesis()}
function confirmAction(title,text,onConfirm){const d=$('#confirmDialog');$('#dialogTitle').textContent=title;$('#dialogText').textContent=text;const handler=()=>{d.removeEventListener('close',handler);if(d.returnValue==='confirm')onConfirm()};d.addEventListener('close',handler);d.showModal();setTimeout(()=>d.querySelector('button[value="cancel"]').focus(),0)}
function reset(){if(qa){notify('QA MODE: скидання learner-state вимкнено.');return}confirmAction('Почати спочатку','Буде очищено навігаційний прогрес, стан вправ і фінальної перевірки. Ваша управлінська карта залишиться збереженою.',()=>{state.route=0;state.formative={};state.assessment={answers:{},passed:false,dirty:false,checked:false,score:null};$$('#assessment input').forEach(i=>i.checked=false);$$('input[name="f1"]').forEach(i=>i.checked=false);$('#f1fb').textContent='';$('#f2fb').hidden=true;$('#f3fb').hidden=true;$('#assessmentStatus').textContent='';save();renderRoute();notify('Прогрес і перевірки очищено. Ваша управлінська карта збережена.');$('#resetBtn').focus()})}
function deletePortfolio(){if(qa){$('#portfolioStatus').textContent='QA MODE: видалення learner-state вимкнено.';return}confirmAction('Видалити мою карту','Ця дія видалить лише шість полів Вашої управлінської карти з локального браузера. Її неможливо скасувати.',()=>{state.portfolio=['','','','','',''];[1,2,3,4,5,6].forEach(i=>$(`#pf${i}`).value='');updateSynthesis();save();$('#portfolioStatus').textContent='Вашу управлінську карту видалено з локального браузера.';$('#deletePortfolio').focus()})}
function formative(n){if(qa){notify('QA MODE: стан вправ не зберігається.');}if(n===1){const v=$('input[name="f1"]:checked');if(!v){$('#f1fb').textContent='Оберіть відповідь, щоб перевірити міркування.';return}if(!qa)state.formative.f1=v.value;$('#f1fb').textContent=v.value==='A'?'Першим має бути управлінське рішення. Саме воно визначає, які дані релевантні, а які лише збільшують інформаційний шум.':'Поверніться до управлінського рішення: воно має бути визначене до розширення переліку даних.';save()}else{$(`#f${n}fb`).hidden=false;if(!qa)state.formative['f'+n]=true;save()}}
const AI1='Проаналізуй лише текст моїх шести полів. Перевір, чи кожен названий набір даних випливає з просторової потреби й чи пояснено його роль у рішенні. Вкажи логічні прогалини або неперевірені припущення. Не вигадуй місцевих фактів, джерел даних чи їх доступності і не обирай рішення замість мене.';
const AI2='На основі лише моїх шести полів сформуй до 6 уточнювальних запитань, які варто поставити відповідальним за дані перед використанням карти в управлінському рішенні. Питай про джерело, актуальність, охоплення, повноту, доступність і придатність. Не виконуй просторовий аналіз, не роби прогнозів і не стверджуй, що невідомі дані існують.';
function buildPrompt(n){const labels=['1. Моє управлінське рішення / питання','2. Яка просторова інформація потрібна','3. Які геодані / GIS-шари допоможуть','4. Де їх шукати / хто відповідає','5. Чи придатні дані для цього рішення','6. Як ці дані будуть використані в рішенні'];const vals=portfolioValues();return (n===1?AI1:AI2)+'\n\nМОЇ ШІСТЬ ПОЛІВ:\n'+labels.map((l,i)=>`${l}: ${vals[i]||'[не заповнено]'}`).join('\n')}
async function copyText(t){try{if(navigator.clipboard&&typeof navigator.clipboard.writeText==='function'){await navigator.clipboard.writeText(t);return true}}catch(e){}const ta=document.createElement('textarea');ta.value=t;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);let ok=false;try{ta.select();ok=document.execCommand('copy')===true}catch(e){ok=false}finally{ta.remove()}return ok}
async function copyPrompt(n){const ok=await copyText(buildPrompt(n));$('#aiStatus').textContent=ok?'Промпт скопійовано. За бажанням відкрийте ChatGPT або Gemini та вставте його вручну. Дані не були автоматично надіслані.':'Не вдалося скопіювати промпт автоматично. Ваші шість полів залишаються в браузері; спробуйте ще раз у браузері з підтримкою копіювання.'}
function assessmentChanged(e){if(!e.target.matches('#assessment input'))return;if(qa){$('#assessmentStatus').textContent='QA MODE: вибір не змінює стан оцінювання.';return;}state.assessment.answers[e.target.name]=e.target.value;if(state.assessment.passed){state.assessment.passed=false;state.assessment.dirty=true;state.assessment.checked=false;state.assessment.score=null;$('#assessmentStatus').textContent='Відповіді змінено після успішної перевірки. Завершення знову заблоковано до нового результату 5/5.';renderCompletion();if(state.route===8)$('#nextBtn').textContent='Далі →'}save()}
function checkAssessment(){if(qa){$('#assessmentStatus').textContent='QA MODE: перевірка відповідей вимкнена, ключі не розкриваються.';return}const keys={q1:'B',q2:'C',q3:'A',q4:'D',q5:'B'};let answered=0,score=0;Object.keys(keys).forEach(q=>{const el=$(`input[name="${q}"]:checked`);if(el){answered++;state.assessment.answers[q]=el.value;if(el.value===keys[q])score++}});if(answered<5){$('#assessmentStatus').textContent='Оберіть одну відповідь у кожному з п’яти запитань.';state.assessment.checked=false;save();return}state.assessment.score=score;state.assessment.checked=true;state.assessment.dirty=false;state.assessment.passed=score===5;$('#assessmentStatus').textContent=score===5?'5/5 — перевірку пройдено. Завершення заняття розблоковано.':`${score}/5 — для завершення потрібно 5/5. Перегляньте логіку заняття і спробуйте ще раз.`;save();renderCompletion();if(state.route===8)$('#nextBtn').textContent=state.assessment.passed?'До завершення →':'Далі →'}
function renderCompletion(){const ok=state.assessment.passed&&!state.assessment.dirty&&state.assessment.checked&&state.assessment.score===5;$('#completionLocked').hidden=ok;$('#completionOpen').hidden=!ok;const btn=$('#nextLessonBtn');btn.textContent='Наступне заняття →';if(ok&&NEXT_LESSON_URL){btn.disabled=false;btn.classList.remove('disabled');btn.title='';btn.dataset.href=NEXT_LESSON_URL}else{btn.disabled=true;btn.classList.add('disabled');btn.removeAttribute('data-href');btn.title='Наступне заняття ще не має контрольованої адреси.'}}
// Local PDF: rasterize text onto browser canvases, then package JPEG pages into a minimal PDF. No network or remote service.
function wrap(ctx,text,max){const words=(text||'—').split(/\s+/);const lines=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>max&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);return lines}
function makePdfPages(vals){const W=1240,H=1754,margin=86,contentW=W-2*margin,pages=[];let c,ctx,y,pageNo=0;function start(){pageNo++;c=document.createElement('canvas');c.width=W;c.height=H;ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#123b63';ctx.font='700 44px Arial, sans-serif';ctx.fillText('Портфель мера',margin,95);ctx.font='700 30px Arial, sans-serif';const title=pageNo===1?'Управлінська карта потреб у геоданих для одного муніципального рішення':'Управлінська карта потреб у геоданих — продовження';let yy=145;for(const l of wrap(ctx,title,contentW)){ctx.fillText(l,margin,yy);yy+=40}y=yy+24}function finish(){pages.push(c.toDataURL('image/jpeg',0.92).split(',')[1])}function ensure(h){if(y+h>H-margin){finish();start()}}start();const labels=['1. Управлінське рішення / питання','2. Просторова інформація, якої потребує рішення','3. Релевантні геодані / GIS-шари','4. Джерело / відповідальний за дані','5. Доступність / придатність','6. Використання в рішенні'];for(let i=0;i<6;i++){ensure(90);ctx.fillStyle='#123b63';ctx.font='700 26px Arial, sans-serif';for(const l of wrap(ctx,labels[i],contentW)){ensure(42);ctx.fillStyle='#123b63';ctx.font='700 26px Arial, sans-serif';ctx.fillText(l,margin,y);y+=34}y+=8;ctx.fillStyle='#172b3a';ctx.font='400 25px Arial, sans-serif';const vls=wrap(ctx,vals[i]||'—',contentW);for(const l of vls){ensure(41);ctx.fillStyle='#172b3a';ctx.font='400 25px Arial, sans-serif';ctx.fillText(l,margin,y);y+=33}ensure(54);ctx.strokeStyle='#dbe4ea';ctx.beginPath();ctx.moveTo(margin,y+16);ctx.lineTo(W-margin,y+16);ctx.stroke();y+=48}finish();return {W,H,pages}}
function bytesFromB64(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
function buildImagePdf(vals){const {W,H,pages}=makePdfPages(vals),PW=595,PH=842,objs=[];function add(s){objs.push(typeof s==='string'?new TextEncoder().encode(s):s);return objs.length}const imageIds=[],contentIds=[],pageIds=[];pages.forEach((b64)=>{const img=bytesFromB64(b64);const head=new TextEncoder().encode(`<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${img.length} >>\nstream\n`),tail=new TextEncoder().encode('\nendstream'),all=new Uint8Array(head.length+img.length+tail.length);all.set(head);all.set(img,head.length);all.set(tail,head.length+img.length);imageIds.push(add(all));const draw=`q ${PW} 0 0 ${PH} 0 0 cm /Im0 Do Q`;contentIds.push(add(`<< /Length ${new TextEncoder().encode(draw).length} >>\nstream\n${draw}\nendstream`));pageIds.push(add('PLACEHOLDER'))});const pagesId=add('PLACEHOLDER'),catalogId=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);pageIds.forEach((id,i)=>{objs[id-1]=new TextEncoder().encode(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PW} ${PH}] /Resources << /XObject << /Im0 ${imageIds[i]} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`)});objs[pagesId-1]=new TextEncoder().encode(`<< /Type /Pages /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] /Count ${pageIds.length} >>`);let parts=[new TextEncoder().encode('%PDF-1.4\n%âãÏÓ\n')],offsets=[0],pos=parts[0].length;objs.forEach((o,i)=>{offsets.push(pos);const h=new TextEncoder().encode(`${i+1} 0 obj\n`),t=new TextEncoder().encode('\nendobj\n');parts.push(h,o,t);pos+=h.length+o.length+t.length});const xrefPos=pos;let x=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)x+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';x+=`trailer\n<< /Size ${objs.length+1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;parts.push(new TextEncoder().encode(x));return new Blob(parts,{type:'application/pdf'})}
async function downloadPdf(){const btn=$('#downloadPdf');$('#portfolioStatus').textContent='Готуємо PDF…';btn.disabled=true;btn.setAttribute('aria-busy','true');await new Promise(r=>requestAnimationFrame(()=>r()));try{const vals=portfolioValues();const blob=buildImagePdf(vals);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='UCAN_Upravlinska_karta_potreb_u_geodanyh.pdf';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);$('#portfolioStatus').textContent='PDF сформовано локально у браузері. Жодні дані не надсилалися на сервер.'}catch(e){$('#portfolioStatus').textContent='Не вдалося сформувати PDF. Ваші дані залишаються у браузері.'}finally{btn.disabled=false;btn.removeAttribute('aria-busy')}}
function restoreFormative(){if(state.formative.f1){const e=$(`input[name="f1"][value="${state.formative.f1}"]`);if(e)e.checked=true;if(state.formative.f1==='A')$('#f1fb').textContent='Першим має бути управлінське рішення. Саме воно визначає, які дані релевантні, а які лише збільшують інформаційний шум.'}if(state.formative.f2)$('#f2fb').hidden=false;if(state.formative.f3)$('#f3fb').hidden=false}
function restoreAssessment(){Object.entries(state.assessment.answers||{}).forEach(([q,v])=>{const el=$(`input[name="${q}"][value="${v}"]`);if(el)el.checked=true});if(state.assessment.checked){$('#assessmentStatus').textContent=state.assessment.passed&&!state.assessment.dirty?'5/5 — перевірку пройдено. Завершення заняття розблоковано.':(state.assessment.dirty?'Відповіді змінено після успішної перевірки. Потрібна нова перевірка 5/5.':`${state.assessment.score}/5 — для завершення потрібно 5/5.`)}}
function init(){load();initStrip();const prev=$('#prevLesson');if(PREVIOUS_LESSON_URL){prev.href=PREVIOUS_LESSON_URL;prev.removeAttribute('aria-disabled');prev.removeAttribute('tabindex')}else{prev.removeAttribute('href');prev.setAttribute('aria-disabled','true');prev.setAttribute('tabindex','-1')}if(qa){$('#qaBadge').hidden=false;state.route=0}renderPortfolio();restoreFormative();restoreAssessment();renderCompletion();renderRoute();$('#prevBtn').addEventListener('click',()=>gotoRoute(state.route-1));$('#nextBtn').addEventListener('click',()=>gotoRoute(state.route+1));$('#resetBtn').addEventListener('click',reset);$('#savePortfolio').addEventListener('click',savePortfolio);$('#deletePortfolio').addEventListener('click',deletePortfolio);$('#downloadPdf').addEventListener('click',downloadPdf);[1,2,3,4,5,6].forEach(i=>$(`#pf${i}`).addEventListener('input',()=>{updateSynthesis();if(!qa){state.portfolio=portfolioValues();save()}}));$$('.formative-check').forEach(b=>b.addEventListener('click',()=>formative(Number(b.dataset.formative))));$$('.copy-prompt').forEach(b=>b.addEventListener('click',()=>copyPrompt(Number(b.dataset.task))));$('#assessment').addEventListener('change',assessmentChanged);$('#checkAssessment').addEventListener('click',checkAssessment);$('#nextLessonBtn').addEventListener('click',()=>{const u=$('#nextLessonBtn').dataset.href;if(u)location.href=u});window.__UCAN_QA__={state,ROUTES,PREVIOUS_LESSON_URL,NEXT_LESSON_URL,gotoRoute,portfolioValues,buildPrompt,buildImagePdf,checkAssessment,copyText,copyPrompt,qa};}
document.addEventListener('DOMContentLoaded',init);
})();
